### PR TITLE
Various non-breaking improvements

### PR DESCRIPTION
**Pull request by ghost**
A happy new year! This PR will accomplish several improvements, but the public API stays the same.

In the code:
- Improve Pylint rating from 4.58 to 9.02 points (with `pylint --disable=C0103 emitter.py`, the camelCase-warning is disabled)
- More logical function order (like in the README.md)
- Docstring improvements
- Various small fixes

The README was edited in order to make the examples working (Why the hell didn't I notice that in the last PR?) and to make various improvements (I want also rewrite the JavaScript README to etablish one standard).

### CODE REVIEW

**Comment by Florimond** [comment]
Happy new year Florian.
Thank you for your contribution. I approved it but I have few questions: 

- What did Pylint take into consideration that incease the rating so dramatically?
- As a non-pythonist, I originally wrote the lib in camelCase, but do you think we should have snake_case aliases for functions?
- Another choice that I made hastly was to mirror the Javascript lib by having a map for event callbacks, instead of storing the callbacks in attributes, and do something like emitter.on_presence = … In your experience, don't you think the latter would make more sense?

**Comment by ghost** [comment]
Hi,

- I never looked why the Pylint rating is so bad, I only fixed the style problems. I reviewed the errors now and the bad rating came from the `"""` of the docstrings - respectively of the strings because Pylint didn't see the strings as docstrings because they was over the functions. Nevertheless there are good advises by the Pylint checks and now the codestyle is better.
- The official [style PEP](https://www.python.org/dev/peps/pep-0008/) says that the snake_case is for functions and variables recommended, but it's okay to keep the CamelCase to keep the libary compatible to old releases.
- Yes, that would be much better. Another point is that the logging parts are repeated serveal times in the libary.

Maybe a fully non backward compatible rewrite would be the best solution for the last two points and a smaller libary. When I've got enough time and desire, I'll take a look at it. (Another idea to consider is to wrap the whole think in a class maybe like this [example](https://github.com/eclipse/paho.mqtt.python/blob/master/examples/client_sub-class.py))...

**Comment by ghost** [comment]
@Florimond, also if there are largely only style changes, will you push the version to PyPI?

**Comment by Florimond** [comment]
Yes I should. I just tried and encountered some issues. I'm a bit busy right now, so I don't want to spend to much time on this. Maybe do you want to give it a try? If so, provide me with your username on pypi and I'll add you as a collaborator.

**Comment by Florimond** [comment]
@flokX I've just uploaded the latest version.

**Pull request merged**
