### PR TITLE
Better security and code tweaks

### PR DESCRIPTION
**Pull request by ghost**
Its better to transport the data well encrypted.

- Enable the secure option by default
- Take the default SSL context without adjustments (to accomplish a better security)
- Remove the superfluous reinitialization of the MQTT client
- Two small code style improvements

### CODE REVIEW

**Comment by ghost** [comment]
Someone here to review? @Florimond

**Comment by Florimond** [comment]
Was going to, but I'm real busy.

I suppose it's fully tested and working?

- Enable the secure option by default
I'd like to check the defaults for the other libs so we keep consistent.

**Comment by ghost** [comment]
Thank you for your time. Everything is tested, sure. Maybe you can also run a small test in your environment.

The new SSL configuration is recommended by the [official Python documentation](https://docs.python.org/3/library/ssl.html?highlight=ssl#best-defaults). I used this way in all of my projects and tested it with the official Emitter servers which works perfect.

The default secure setting in the JavaScript libary is false, but I think we should make it more secure starting here. By the way: The adjustment to the docs is on the way.

**Comment by Florimond** [comment]
Then should we go from 1.0.3 to 1.1.0, so as not to surprise people whose code use the default parameters?

setup.py
> setup(
>     name='emitter-io',
> 
>     version='1.0.3'

Edit: or is 2.0.0 too much for such small change? What do you think?

**Review by Florimond — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Oh you were quick... 🚀 
I was going to write that maybe we should stick to the [Semantic Versioning](https://semver.org/#spec-item-7).

**Comment by Florimond** [comment]
So you were actually for a 2.0.0 ?

**Comment by ghost** [comment]
No, I agree with 1.1.0 because the PR introduced new _backwards compatible functionality_.
Everything is okay. Sorry when it was unclear.

**Pull request merged**
