### PR TITLE
Code Refactored

### PR DESCRIPTION
**Pull request by dharanad**
Removed redundant code and fixed typo's.

### CODE REVIEW

**Comment by Florimond** [comment]
Thank you for fixing my typos.

However, you removed

```python
if "secure" not in options:
    options["secure"] = False
```

Which means this code won't work if there is no "secure" key provided by the user :

```python
defaultConnectOptions = {
    "host": "api.emitter.io",
    "port": 443 if options["secure"] else 8080,
    "keepalive": 30,
    "secure": False
}
```

What could be removed though, is the last line "secure": False.

The idea is that if people don't set the secure flag it should be not secure by default. Then they should never have to set the port, whether they did set the secure flag or not.

What do you think?

**Comment by dharanad** [comment]
Opps 😔 your right. Its my fault.  i got the logic now.

**Review by Florimond — CHANGES_REQUESTED** [review]
As discussed, leave this :

```python
if "secure" not in options:
    options["secure"] = False
```

Remove the redundant "secure": False from there...
```python
defaultConnectOptions = {
    "host": "api.emitter.io",
    "port": 443 if options["secure"] else 8080,
    "keepalive": 30,
    "secure": False
}
```

**Comment by dharanad** [comment]
Made the changes. Hope it is ready to merger 👍

**Review by Florimond — APPROVED** [review]
LGTM

**Pull request merged**
