### PR TITLE
Improve setup

### PR DESCRIPTION
**Pull request by ghost**
What did this PR?
- Remove uneeded complexity from the setup.py
- Stick with the setup.py to the [official example](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py)

Notes:
- The README.rst was removed because now the README.md is used to populate the PIP description (We have to look how the HTML-tags in it will look at the PyPi page...)
- The argument `license` was removed, because PyPi uses the classifier

Another point to discuss: Why is the package still in the beta phase? There are features like the `username` in the presence which are missing, but the package itself is (in my experience) always stable.

### CODE REVIEW

**Comment by ghost** [comment]
I also added a few tweaks to the README which I wanted to do since the rewriting.

@Florimond Why did you wrote 
> This SDK is available as a pip package _BUT it is no longer_:

?

**Comment by Florimond** [comment]
A remnant from when I wanted to remove the pip package. Thank you from pointing it out.

About the beta phase, which one do you think would be more appropriate?

**Comment by ghost** [comment]
I don't know how big is the userspace or how good the packege is tested in the different environments but my experience was that it was always stable.
So in my view the only option is to think about bumping it in the stage 5 - stable.

**Comment by Florimond** [comment]
Ok, seems reasonable to me.

**Review by Florimond — CHANGES_REQUESTED** [review]
Stage 5 - Stable

**Review by Florimond — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
In my view, you can merge the changes now.

**Pull request merged**
